import type { Book } from "@/types/book";

export const mockBooks: Book[] = [
  {
    id: "1",
    slug: "sessiz-zihin",
    title: "Sessiz Zihin",
    author: "Elif Aras",
    publisher: "Kitapix Yayınları",
    cover: "/images/books/sessiz-zihin.svg",
    price: 289,
    originalPrice: 349,
    rating: 4.7,
    reviewCount: 214,
    badge: "Sana Uygun",
  },
  {
    id: "2",
    slug: "zamanin-kiyisinda",
    title: "Zamanın Kıyısında",
    author: "Deniz Kaya",
    publisher: "Kuzey Kitap",
    cover: "/images/books/zamanin-kiyisinda.svg",
    price: 319,
    rating: 4.5,
    reviewCount: 168,
    badge: "Editör Seçimi",
  },
  {
    id: "3",
    slug: "odaklanma-sanati",
    title: "Odaklanma Sanatı",
    author: "Selin Aydın",
    publisher: "Mavi Sayfa",
    cover: "/images/books/odaklanma-sanati.svg",
    price: 259,
    originalPrice: 299,
    rating: 4.6,
    reviewCount: 321,
    badge: "Çok Satan",
  },
  {
    id: "4",
    slug: "yeniden-baslamak",
    title: "Yeniden Başlamak",
    author: "Mert Ekin",
    publisher: "Yeni Nesil Yayınları",
    cover: "/images/books/yeniden-baslamak.svg",
    price: 275,
    rating: 4.3,
    reviewCount: 97,
    badge: "Yeni",
  },
  {
    id: "5",
    slug: "gece-yolculugu",
    title: "Gece Yolculuğu",
    author: "Kerem Öztürk",
    publisher: "Kuzey Kitap",
    cover: "/images/books/gece-yolculugu.svg",
    price: 299,
    originalPrice: 365,
    rating: 4.4,
    reviewCount: 142,
  },
  {
    id: "6",
    slug: "gunluk-hayat-icin-felsefe",
    title: "Günlük Hayat İçin Felsefe",
    author: "Elif Aras",
    publisher: "Kitapix Yayınları",
    cover: "/images/books/gunluk-hayat-icin-felsefe.svg",
    price: 339,
    rating: 4.8,
    reviewCount: 256,
    badge: "Editör Seçimi",
  },
  {
    id: "7",
    slug: "merakli-cocuklar-icin-bilim",
    title: "Meraklı Çocuklar İçin Bilim",
    author: "Deniz Kaya",
    publisher: "Mavi Sayfa",
    cover: "/images/books/merakli-cocuklar-icin-bilim.svg",
    price: 249,
    originalPrice: 289,
    rating: 4.6,
    reviewCount: 188,
    badge: "Çok Satan",
  },
  {
    id: "8",
    slug: "kucuk-adimlar",
    title: "Küçük Adımlar",
    author: "Selin Aydın",
    publisher: "Yeni Nesil Yayınları",
    cover: "/images/books/kucuk-adimlar.svg",
    price: 229,
    rating: 4.2,
    reviewCount: 76,
    badge: "Yeni",
  },
];
